export const CHANGE_SEARCH_FIELD_TYPE = 'CHANGE_SEARCH_FIELD';

export const GET_ROBOTS_REQUEST_TYPE = 'GET_ROBOTS_REQUEST';
export const GET_ROBOTS_SUCCESS_TYPE = 'GET_ROBOTS_SUCCESS';
export const GET_ROBOTS_FAILURE_TYPE = 'GET_ROBOTS_FAILURE';
